from Data.Stockdata import get_stock_market_data_basic
from Data.Stockdata import get_stock_market_data_basic_today
from Data.Stockdata import get_stock_market_data_get_info
from Data.Stockdata import get_stock_market_data_get_info_today


from Regression.Regression import LogisticRegression
from Regression.Regression import LinearRegression
from Regression.Regression import RandomForestRegressPredict
from Regression.Regression import decision_tree_predict
from Regression.Regression import polynomial_regression_predict
